### ISSUE TITLE
Single click not opening files

### ISSUE THREAD

**Issue by DavidLeoni** [stemcstudio/stemcstudio#21]
Hi

First off, congrats for the project, looks very promising and fun to work with!

Editor is working fine, but I find that file opening is a bit odd. When I single-click on files which have never been opened before (so are shown in dark grey), nothing happens. If I double click on them, they get opened and their link turns white. If I then single-click on files with white links they actually get opened right away. This may mislead users into thinking editor is not working.

Tested v2.21.19 on Chromium 55.0.2883.87 and also  Firefox 50.1.0 on Ubuntu 16.04

**Comment by stemcstudio** [comment]
David,
The absence of an action upon single-click reflects a design intention that single-click would give a preview of a file without actually opening it. Thus, you might single-click a number of files in succession but only the last would be in the view. Further action such as editing would actually open the file. This is not yet implemented. Your confusion has been noted by others and I will be considering a solution soon.
Thanks,
David

**Comment by stemcstudio** [comment]
David,
In version 2.21.70, the only action on a file is a click, which opens the file and makes it the selected file.
Thanks for your feedback and support,
David

**Comment by stemcstudio** [comment]
A possible future enhancement is to close files that are opened but not changed.
