### ISSUE TITLE
Support jumping between words with control left / right

### ISSUE THREAD

**Issue by DavidLeoni** [stemcstudio/stemcstudio#52]
It would be pretty handy if the editor supported control left / right for moving rapidly between words, as commonly allowed in most editors. Without this editing experience can get burdensome. 

Tested in Firefox 61 /  Chrome  67.0.3396.99  Ubuntu 16.04

**Comment by stemcstudio** [comment]
Thanks for you feedback David!
This has now been implemented in version 2.50.0.
Some other word-based commands have also been implemented.
Use Ctrl-Alt-H (Windows or Linux) or Command-Alt-H (Mac) (when an editor has the keyboard focus) to see the keyboard shortcuts.
