### ISSUE TITLE
Template for Moodle Formulas-Filter with JSXGraph 

### ISSUE THREAD

**Issue by bujowi** [stemcstudio/stemcstudio#56]
Moodle Formulas-Plugin is used at over 1000 Moodle sites worldwide. The JSXGraph-extension offers a good integration of graphs into Formulas questions.
https://github.com/jsxgraph/moodle-filter_jsxgraph/tree/master/libs/formulas_extension
(uses: https://github.com/jsxgraph/moodle-filter_jsxgraph)

**Could a template be added to facilitate the programming of JS and JSXGraph code in the context of this filter?
- At least the IDE should know the class "JSXQuestion" as documented on GitHub**
That could be an awsome help when authoring these questions

**Comment by stemcstudio** [comment]
@bujowi,

Thanks for your question. I'm new to understanding the Moodle extension mechanism that you are referring to. My rudimentary understanding leads me to believe that an extension is developed by starting with a JavaScript library representing some HTML view and then provide the shim that exposes it as a Moodle plugin. I guess that this provides a tighter integration that simply embedding an iframe. While embedding is possible, STEMCstudio is not currently offered as a library, although I do have an eye on moving the workspace page in that direction. Once that is done, I believe a Moodle extension would be possible.

I would be interested to hear how you think a tighter integration with the Moodle might provide value to the user. What would this look like?

I like the idea.

**Comment by stemcstudio** [comment]
Integration with the Moodle formulas plugin and the JSXGraph plugin is possible by using the code specially generated for Moodle as script.

**Comment by stemcstudio** [comment]
Implemented using the "Show Generated Code" menu item in the "Workspace Settings" menu. But this workflow is likely to become obsolete now that STEMCviewer is available.
