### ISSUE TITLE
Catch Ctrl+S Key & change the Behavior to push the Document to the Github Repo

### ISSUE THREAD

**Issue by SpocWeb** [stemcstudio/stemcstudio#68]
Hi, first of all: Congratulations for your StemCStudio and the Videos about it. I find it very interesting and productive. 

Just an idea: I (and many other long-time developers) have a Habit of frequently pressing Ctrl+S in our Editors to prevent losing work. 

With Web-Editors this pops up the "Save Web Page" Dialog by Default, which is obviously not what you want. 
Some Editors (like Azure DevOps) manage to capture the Keystroke and instead save the currently edited Document. 

This would be a nice feature for StemCStudio too.
Best regards...

**Comment by geometryzen** [comment]
As things currently stand, your work is being saved to Local Storage in the background. Updating GitHub is a distinct step. If Ctrl+S were implemented in a way similar to editors it would merely force the save to Local Storage. Updating GitHub might be considered surprising behavior. What do you think?

**Comment by SpocWeb** [comment]
Saving to local Storage would be fine for me, too. Currently the Browser 'Save As' Dialog pops up which is definitely not what any developer wants most of the time. 
So feel free to to what you want but capture the Ctrl-S Keystroke. 
Best Regards...

**Comment by stemcstudio** [comment]
Agreed, that Ctrl-S reflex is hard to tame.

**Comment by SpocWeb** [comment]
At least for old-school devs like me... ;-)

**Comment by stemcstudio** [comment]
Ctrl-S now forces a save to Local Storage.

**Comment by stemcstudio** [comment]
Completed.
